spring:
  application:
    name: user-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: postgres
    password: '{cipher}75e424ebacc4ac532c4c4154cc20345d65c08acb2b3cc09ac790d1f32862c4a5'
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8081

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: Kuqzu4F0s62x3U6tySmXM8ddqa2wEqD5
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: user-service
    description: Ticketing Application User Service

resilience4j:
  circuitbreaker:
    instances:
      project-service:
        baseConfig: default
      task-service:
        baseConfig: default
        waitDurationInOpenState: 20000
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 2

